// 游戏数据 - 30个游戏
const gamesData = [
    // ========== 益智类 ==========
    {
        id: "2048",
        name: "2048",
        nameEn: "2048",
        nameJa: "2048",
        category: "puzzle",
        categoryName: "益智",
        icon: "🔢",
        cover: "assets/covers/2048.jpg",
        video: "assets/videos/2048.mp4",
        url: "games/2048/index.html",
        description: "经典数字合并游戏,滑动合并相同数字,目标是得到2048!",
        descriptionEn: "Classic number merging game. Slide to merge matching numbers and reach 2048!",
        descriptionJa: "数字を合体させる定番ゲーム。スライドして同じ数字を合わせ、2048を目指そう！",
        controls: "使用方向键或滑动屏幕",
        controlsEn: "Arrow keys or swipe",
        controlsJa: "矢印キーまたはスワイプ",
        featured: true,
        createdAt: "2026-01-31 01:41"
    },
    {
        id: "tetris",
        name: "俄罗斯方块",
        nameEn: "Tetris",
        nameJa: "テトリス",
        category: "puzzle",
        categoryName: "益智",
        icon: "🧱",
        cover: "assets/covers/俄罗斯方块.jpg",
        video: "assets/videos/俄罗斯方块.mp4",
        url: "games/tetris/index.html",
        description: "经典方块消除游戏,旋转下落方块填满行!",
        descriptionEn: "Classic block-clearing game. Rotate falling blocks to complete rows!",
        descriptionJa: "定番ブロック消しゲーム。落ちてくるブロックを回転させて行を揃えよう！",
        controls: "方向键移动,↑旋转",
        controlsEn: "Arrow keys to move, ↑ to rotate",
        controlsJa: "矢印キーで移動、↑で回転",
        featured: true,
        createdAt: "2026-01-31 23:57"
    },
    {
        id: "memory",
        name: "记忆翻牌",
        nameEn: "Memory Match",
        nameJa: "神経衰弱",
        category: "puzzle",
        categoryName: "益智",
        icon: "🃏",
        cover: "assets/covers/memory.jpg",
        video: "assets/videos/memory.mkv",
        url: "games/memory/index.html",
        description: "翻开卡片找到匹配的图案,锻炼你的记忆力!",
        descriptionEn: "Flip cards to find matching pairs. Train your memory!",
        descriptionJa: "カードをめくってペアを見つけよう。記憶力を鍛えよう！",
        controls: "点击卡片翻转",
        controlsEn: "Click cards to flip",
        controlsJa: "カードをクリックしてめくる",
        createdAt: "2026-01-31 23:57"
    },
    {
        id: "minesweeper",
        name: "扫雷",
        nameEn: "Minesweeper",
        nameJa: "マインスイーパー",
        category: "puzzle",
        categoryName: "益智",
        icon: "💣",
        cover: "assets/covers/minesweeper.jpg",
        video: "assets/videos/minesweeper.mkv",
        url: "games/minesweeper/index.html",
        description: "经典扫雷游戏,根据数字提示避开地雷!",
        descriptionEn: "Classic Minesweeper. Use number clues to avoid mines!",
        descriptionJa: "定番マインスイーパー。数字のヒントで地雷を避けよう！",
        controls: "左键挖开,右键标记",
        controlsEn: "Left click to dig, right click to flag",
        controlsJa: "左クリックで開く、右クリックで旗",
        createdAt: "2026-01-31 23:57"
    },
    {
        id: "puzzle15",
        name: "数字华容道",
        nameEn: "15 Puzzle",
        nameJa: "15パズル",
        category: "puzzle",
        categoryName: "益智",
        icon: "🔲",
        cover: "assets/covers/puzzle15.jpg",
        video: "assets/videos/puzzle15.mkv",
        url: "games/puzzle15/index.html",
        description: "经典15数字滑块拼图,把数字按顺序排好!",
        descriptionEn: "Classic 15-tile sliding puzzle. Arrange numbers in order!",
        descriptionJa: "定番15パズル。数字を順番に並べ替えよう！",
        controls: "点击方块滑动",
        controlsEn: "Click tiles to slide",
        controlsJa: "タイルをクリックしてスライド",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "sokoban",
        name: "推箱子",
        nameEn: "Sokoban",
        nameJa: "倉庫番",
        category: "puzzle",
        categoryName: "益智",
        icon: "📦",
        cover: "assets/covers/sokoban.jpg",
        video: "assets/videos/sokoban.mkv",
        url: "games/sokoban/index.html",
        description: "经典推箱子游戏,把箱子推到指定位置!",
        descriptionEn: "Classic Sokoban. Push boxes to their target positions!",
        descriptionJa: "定番倉庫番。箱を目標の位置に押していこう！",
        controls: "方向键移动",
        controlsEn: "Arrow keys to move",
        controlsJa: "矢印キーで移動",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "maze",
        name: "迷宫",
        nameEn: "Maze",
        nameJa: "迷路",
        category: "puzzle",
        categoryName: "益智",
        icon: "🌀",
        cover: "assets/covers/maze.jpg",
        video: "assets/videos/maze.mkv",
        url: "games/maze/index.html",
        description: "随机生成迷宫,找到出口!",
        descriptionEn: "Navigate through randomly generated mazes to find the exit!",
        descriptionJa: "ランダム生成の迷路を突破して出口を見つけよう！",
        controls: "方向键移动",
        controlsEn: "Arrow keys to move",
        controlsJa: "矢印キーで移動",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "match3",
        name: "消消乐",
        nameEn: "Match 3",
        nameJa: "マッチ3",
        category: "puzzle",
        categoryName: "益智",
        icon: "💎",
        cover: "assets/covers/match3.jpg",
        video: "assets/videos/match3.mkv",
        url: "games/match3/index.html",
        description: "三消游戏,交换相邻宝石消除!",
        descriptionEn: "Match-3 puzzle game. Swap adjacent gems to make matches!",
        descriptionJa: "3つ揃えパズル。隣の宝石を入れ替えて揃えよう！",
        controls: "点击交换宝石",
        controlsEn: "Click to swap gems",
        controlsJa: "クリックで宝石を入れ替え",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "guessnumber",
        name: "猜数字",
        nameEn: "Guess the Number",
        nameJa: "数当て",
        category: "puzzle",
        categoryName: "益智",
        icon: "🎯",
        cover: "assets/covers/guessnumber.jpg",
        video: "assets/videos/guessnumber.mkv",
        url: "games/guessnumber/index.html",
        description: "猜1-100之间的数字,根据提示找到答案!",
        descriptionEn: "Guess a number between 1-100 using hints!",
        descriptionJa: "1-100の数字をヒントを使って当てよう！",
        controls: "输入数字猜测",
        controlsEn: "Type a number to guess",
        controlsJa: "数字を入力して推測",
        createdAt: "2026-02-01 00:22"
    },

    // ========== 街机类 ==========
    {
        id: "snake",
        name: "贪吃蛇",
        nameEn: "Snake",
        nameJa: "スネーク",
        category: "arcade",
        categoryName: "街机",
        icon: "🐍",
        cover: "assets/covers/贪吃蛇.jpg",
        video: "assets/videos/贪吃蛇.mp4",
        url: "games/snake/index.html",
        description: "控制小蛇吃苹果变长,不要撞墙或咬到自己!",
        descriptionEn: "Control the snake to eat apples and grow. Don't hit walls or yourself!",
        descriptionJa: "ヘビを操作してりんごを食べて成長しよう。壁や自分にぶつからないで！",
        controls: "使用方向键控制方向",
        controlsEn: "Arrow keys to control direction",
        controlsJa: "矢印キーで方向操作",
        featured: true,
        createdAt: "2026-01-31 01:41"
    },
    {
        id: "flappy",
        name: "Flappy Bird",
        nameEn: "Flappy Bird",
        nameJa: "Flappy Bird",
        category: "arcade",
        categoryName: "街机",
        icon: "🐦",
        cover: "assets/covers/flappy-bird.jpg",
        video: "assets/videos/flappy-bird.mkv",
        url: "games/flappy/index.html",
        description: "点击屏幕让小鸟飞翔,躲避管道障碍!",
        descriptionEn: "Tap to make the bird fly. Dodge the pipes!",
        descriptionJa: "タップで鳥を飛ばそう。土管を避けて！",
        controls: "点击屏幕或按空格",
        controlsEn: "Click or press Space",
        controlsJa: "クリックまたはスペースキー",
        createdAt: "2026-01-31 23:57"
    },
    {
        id: "breakout",
        name: "打砖块",
        nameEn: "Breakout",
        nameJa: "ブロック崩し",
        category: "arcade",
        categoryName: "街机",
        icon: "🧱",
        cover: "assets/covers/breakout.jpg",
        video: "assets/videos/breakout.mkv",
        url: "games/breakout/index.html",
        description: "控制挡板反弹球打碎所有砖块!",
        descriptionEn: "Control the paddle to bounce the ball and break all bricks!",
        descriptionJa: "パドルを操作してボールを距し、全てのブロックを壊そう！",
        controls: "鼠标或触屏移动挡板",
        controlsEn: "Mouse or touch to move paddle",
        controlsJa: "マウスまたはタッチでパドル移動",
        createdAt: "2026-01-31 23:57"
    },
    {
        id: "spaceshooter",
        name: "太空射击",
        nameEn: "Space Shooter",
        nameJa: "スペースシューター",
        category: "arcade",
        categoryName: "街机",
        icon: "🚀",
        cover: "assets/covers/spaceshooter.jpg",
        video: "assets/videos/spaceshooter.mkv",
        url: "games/spaceshooter/index.html",
        description: "驾驶飞船消灭外星入侵者!",
        descriptionEn: "Pilot your ship and destroy alien invaders!",
        descriptionJa: "宇宙船を操縦してエイリアンを撃退しよう！",
        controls: "←→移动,空格射击",
        controlsEn: "←→ to move, Space to shoot",
        controlsJa: "←→で移動、スペースで射撃",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "runner",
        name: "无尽跑酷",
        nameEn: "Endless Runner",
        nameJa: "エンドレスラン",
        category: "arcade",
        categoryName: "街机",
        icon: "🏃",
        cover: "assets/covers/runner.jpg",
        video: "assets/videos/runner.mkv",
        url: "games/runner/index.html",
        description: "跳跃躲避障碍,收集金币!",
        descriptionEn: "Jump over obstacles and collect coins!",
        descriptionJa: "障害物を飛び越えてコインを集めよう！",
        controls: "↑跳跃,↓滑行",
        controlsEn: "↑ to jump, ↓ to slide",
        controlsJa: "↑でジャンプ、↓でスライド",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "ninjajump",
        name: "跳跃忍者",
        nameEn: "Ninja Jump",
        nameJa: "ニンジャジャンプ",
        category: "arcade",
        categoryName: "街机",
        icon: "🥷",
        cover: "assets/covers/ninjajump.jpg",
        video: "assets/videos/ninjajump.mkv",
        url: "games/ninjajump/index.html",
        description: "控制忍者跳上平台,不断向上!",
        descriptionEn: "Control the ninja to jump on platforms and climb higher!",
        descriptionJa: "忍者を操作してプラットフォームに飛び乗り、どんどん上へ！",
        controls: "←→移动",
        controlsEn: "←→ to move",
        controlsJa: "←→で移動",
        createdAt: "2026-02-01 00:33"
    },
    {
        id: "fruitslice",
        name: "切水果",
        nameEn: "Fruit Slice",
        nameJa: "フルーツスライス",
        category: "arcade",
        categoryName: "街机",
        icon: "🍉",
        cover: "assets/covers/fruitslice.jpg",
        video: "assets/videos/fruitslice.mkv",
        url: "games/fruitslice/index.html",
        description: "滑动切开水果,小心炸弹!",
        descriptionEn: "Swipe to slice fruits. Watch out for bombs!",
        descriptionJa: "スワイプでフルーツを切ろう。爆弾に注意！",
        controls: "滑动屏幕切水果",
        controlsEn: "Swipe to slice",
        controlsJa: "スワイプでスライス",
        createdAt: "2026-02-01 00:34"
    },
    {
        id: "knifehit",
        name: "飞刀",
        nameEn: "Knife Hit",
        nameJa: "ナイフヒット",
        category: "arcade",
        categoryName: "街机",
        icon: "🔪",
        cover: "assets/covers/knifehit.jpg",
        video: "assets/videos/knifehit.mkv",
        url: "games/knifehit/index.html",
        description: "把飞刀投向旋转的木桩,别碰到其他刀!",
        descriptionEn: "Throw knives at the spinning log. Don't hit other knives!",
        descriptionJa: "回転する丸太にナイフを投げよう。他のナイフに当てるな！",
        controls: "点击或空格投刀",
        controlsEn: "Click or Space to throw",
        controlsJa: "クリックまたはスペースで投げる",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "catchfruits",
        name: "接水果",
        nameEn: "Catch Fruits",
        nameJa: "フルーツキャッチ",
        category: "arcade",
        categoryName: "街机",
        icon: "🧺",
        cover: "assets/covers/catchfruits.jpg",
        video: "assets/videos/catchfruits.mkv",
        url: "games/catchfruits/index.html",
        description: "移动篮子接住下落的水果!",
        descriptionEn: "Move the basket to catch falling fruits!",
        descriptionJa: "カゴを動かして落ちてくるフルーツをキャッチ！",
        controls: "←→移动或鼠标",
        controlsEn: "←→ or mouse to move",
        controlsJa: "←→またはマウスで移動",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "dodge",
        name: "躲避球",
        nameEn: "Dodge Ball",
        nameJa: "ドッジボール",
        category: "arcade",
        categoryName: "街机",
        icon: "⚡",
        cover: "assets/covers/dodge.jpg",
        video: "assets/videos/dodge.mkv",
        url: "games/dodge/index.html",
        description: "控制圆点躲避红色方块!",
        descriptionEn: "Control the dot to dodge red blocks!",
        descriptionJa: "ドットを操作して赤いブロックを避けよう！",
        controls: "鼠标或触屏移动",
        controlsEn: "Mouse or touch to move",
        controlsJa: "マウスまたはタッチで移動",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "stack",
        name: "堆叠高塔",
        nameEn: "Stack Tower",
        nameJa: "スタックタワー",
        category: "arcade",
        categoryName: "街机",
        icon: "🏗️",
        cover: "assets/covers/stack.jpg",
        video: "assets/videos/stack.mkv",
        url: "games/stack/index.html",
        description: "对准时机放置方块,堆建高塔!",
        descriptionEn: "Time your drops to stack blocks and build a tower!",
        descriptionJa: "タイミングを合わせてブロックを積み上げ、タワーを建てよう！",
        controls: "点击或空格放置",
        controlsEn: "Click or Space to place",
        controlsJa: "クリックまたはスペースで配置",
        createdAt: "2026-02-01 00:35"
    },
    {
        id: "pinball",
        name: "弹球",
        nameEn: "Pinball",
        nameJa: "ピンボール",
        category: "arcade",
        categoryName: "街机",
        icon: "🎮",
        cover: "assets/covers/pinball.jpg",
        video: "assets/videos/pinball.mkv",
        url: "games/pinball/index.html",
        description: "经典弹球游戏,击打目标得高分!",
        descriptionEn: "Classic pinball game. Hit targets for high scores!",
        descriptionJa: "定番ピンボール。ターゲットを撃ってハイスコアを目指そう！",
        controls: "鼠标移动挡板",
        controlsEn: "Mouse to move paddle",
        controlsJa: "マウスでパドル移動",
        createdAt: "2026-02-01 00:22"
    },

    // ========== 竞速类 ==========
    {
        id: "racing",
        name: "极速赛车",
        nameEn: "Speed Racing",
        nameJa: "レーシング",
        category: "racing",
        categoryName: "竞速",
        icon: "🏎️",
        cover: "assets/covers/racing.jpg",
        video: "assets/videos/racing.mkv",
        url: "games/racing/index.html",
        description: "切换车道躲避其他车辆!",
        descriptionEn: "Switch lanes to dodge other vehicles!",
        descriptionJa: "車線を切り替えて他の車両を避けよう！",
        controls: "←→切换车道",
        controlsEn: "←→ to switch lanes",
        controlsJa: "←→で車線変更",
        createdAt: "2026-02-01 00:22"
    },

    // ========== 体育类 ==========
    {
        id: "pong",
        name: "乒乓球",
        nameEn: "Pong",
        nameJa: "ポン",
        category: "sports",
        categoryName: "体育",
        icon: "🏓",
        cover: "assets/covers/pong.jpg",
        video: "assets/videos/pong.mkv",
        url: "games/pong/index.html",
        description: "经典双人乒乓球对战!",
        descriptionEn: "Classic two-player Pong battle!",
        descriptionJa: "定番の2人対戦ポン！",
        controls: "W/S和↑/↓控制",
        controlsEn: "W/S and ↑/↓ to control",
        controlsJa: "W/Sと↑/↓で操作",
        createdAt: "2026-01-31 23:57"
    },
    {
        id: "football",
        name: "点球大战",
        nameEn: "Penalty Kick",
        nameJa: "PK戦",
        category: "sports",
        categoryName: "体育",
        icon: "⚽",
        cover: "assets/covers/football.jpg",
        video: "assets/videos/football.mkv",
        url: "games/football/index.html",
        description: "点击方向射门,骗过守门员!",
        descriptionEn: "Click to aim and shoot. Outsmart the goalkeeper!",
        descriptionJa: "クリックで狙ってシュート。GKを騙そう！",
        controls: "点击射门方向",
        controlsEn: "Click to aim and shoot",
        controlsJa: "クリックで狙ってシュート",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "basketball",
        name: "投篮机",
        nameEn: "Basketball Shoot",
        nameJa: "バスケットボール",
        category: "sports",
        categoryName: "体育",
        icon: "🏀",
        cover: "assets/covers/basketball.jpg",
        video: "assets/videos/basketball.mkv",
        url: "games/basketball/index.html",
        description: "拖动设置力度和角度投篮!",
        descriptionEn: "Drag to set power and angle for the perfect shot!",
        descriptionJa: "ドラッグで力と角度を調整してシュート！",
        controls: "拖动投篮",
        controlsEn: "Drag to shoot",
        controlsJa: "ドラッグでシュート",
        createdAt: "2026-02-01 00:22"
    },

    // ========== 棋牌类 ==========
    {
        id: "tictactoe",
        name: "井字棋",
        nameEn: "Tic Tac Toe",
        nameJa: "三目並べ",
        category: "board",
        categoryName: "棋牌",
        icon: "⭕",
        cover: "assets/covers/tictactoe.jpg",
        video: "assets/videos/tictactoe.mkv",
        url: "games/tictactoe/index.html",
        description: "经典井字棋,三子连线获胜!",
        descriptionEn: "Classic Tic Tac Toe. Get three in a row to win!",
        descriptionJa: "定番三目並べ。3つ揃えたら勝ち！",
        controls: "点击格子落子",
        controlsEn: "Click a cell to place",
        controlsJa: "マスをクリックして置く",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "reversi",
        name: "黑白棋",
        nameEn: "Reversi",
        nameJa: "リバーシ",
        category: "board",
        categoryName: "棋牌",
        icon: "⚫",
        cover: "assets/covers/reversi.jpg",
        video: "assets/videos/reversi.mkv",
        url: "games/reversi/index.html",
        description: "翻转对手的棋子,占领更多格子!",
        descriptionEn: "Flip your opponent's pieces to dominate the board!",
        descriptionJa: "相手の駒をひっくり返して盤面を制覇しよう！",
        controls: "点击落子",
        controlsEn: "Click to place",
        controlsJa: "クリックで置く",
        createdAt: "2026-02-01 00:22"
    },

    // ========== 休闲类 ==========
    {
        id: "typing",
        name: "打字练习",
        nameEn: "Typing Practice",
        nameJa: "タイピング練習",
        category: "casual",
        categoryName: "休闲",
        icon: "⌨️",
        cover: "assets/covers/typing.jpg",
        video: "assets/videos/typing.mkv",
        url: "games/typing/index.html",
        description: "打出下落的字母,提高打字速度!",
        descriptionEn: "Type falling letters to improve your typing speed!",
        descriptionJa: "落ちてくる文字をタイプしてタイピング速度を上げよう！",
        controls: "键盘打字",
        controlsEn: "Keyboard to type",
        controlsJa: "キーボードでタイピング",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "colorswitch",
        name: "颜色切换",
        nameEn: "Color Switch",
        nameJa: "カラースイッチ",
        category: "casual",
        categoryName: "休闲",
        icon: "🎨",
        cover: "assets/covers/colorswitch.jpg",
        video: "assets/videos/colorswitch.mkv",
        url: "games/colorswitch/index.html",
        description: "快速切换颜色匹配目标!",
        descriptionEn: "Quickly switch colors to match the target!",
        descriptionJa: "素早く色を切り替えてターゲットに合わせよう！",
        controls: "点击切换颜色",
        controlsEn: "Click to switch color",
        controlsJa: "クリックで色を切り替え",
        createdAt: "2026-02-01 00:22"
    },
    {
        id: "reaction",
        name: "反应测试",
        nameEn: "Reaction Test",
        nameJa: "反応テスト",
        category: "casual",
        categoryName: "休闲",
        icon: "⚡",
        cover: "assets/covers/reaction.jpg",
        video: "assets/videos/reaction.mkv",
        url: "games/reaction/index.html",
        description: "测试你的反应速度!",
        descriptionEn: "Test your reaction speed!",
        descriptionJa: "反応速度をテストしよう！",
        controls: "变绿时点击",
        controlsEn: "Click when it turns green",
        controlsJa: "緑になったらクリック",
        createdAt: "2026-02-01 00:22"
    }
];
