export const site = {
  origin: "https://gametest.online",
  name: "GameZone",
  updated: "2026-09-21",
  issues: "https://github.com/bingjokerx-ops/P001-game-zone/issues",
};

// These describe the actual controls and session format, not audience/traffic estimates.
export const desktopOnly = new Set(["spaceshooter"]);
export const twoPlayers = new Set(["pong", "tictactoe", "reversi"]);
export const shortGames = new Set([
  "reaction",
  "colorswitch",
  "typing",
  "football",
  "basketball",
  "guessnumber",
]);
export const featured = [
  "2048",
  "minesweeper",
  "memory",
  "sokoban",
  "puzzle15",
  "reaction",
];
export const words = {
  zh: {
    lang: "zh-CN",
    home: "游戏大厅",
    learn: "练习室",
    about: "关于本站",
    privacy: "隐私说明",
    feedback: "反馈问题",
    all: "全部游戏",
    search: "搜索游戏名称或玩法",
    filter: "选择游戏类型",
    favorite: "收藏",
    saved: "已收藏",
    favorites: "我的收藏",
    recent: "最近玩过",
    local: "收藏和游玩记录只保存在当前浏览器。",
    start: "开始游戏",
    ready: "准备好了吗？",
    load: "点击开始后加载游戏。先看操作，再开始这一局。",
    fullscreen: "全屏游戏",
    standalone: "单独打开游戏",
    restart: "重新加载",
    intro: "游戏介绍",
    gameplay: "怎么玩",
    controls: "操作说明",
    scoring: "计分与结束",
    tips: "新手技巧",
    related: "接下来玩什么",
    guide: "想明白，再动手",
    guideIntro: "用可操作的例题理解规则，带着一个具体策略开始下一局。",
    minutes: "短局练习",
    ownPace: "按自己的节奏",
    solo: "单人",
    duo: "同屏双人",
    keyboard: "键盘",
    touch: "支持触屏",
    searchEmpty: "没有找到符合条件的游戏。试试其他关键词或清除筛选。",
    reset: "清除筛选",
    total: "款游戏",
    hero: "休息一下，\n认真玩一局。",
    promise: "免下载的小游戏与实用玩法指南。先选一种心情，再找到你的下一局。",
    featured: "从这几款开始",
    featuredText: "合并、推理、记忆：不用追赶进度，先把一个小目标玩明白。",
    browse: "浏览所有游戏",
    tryLesson: "试试互动练习",
    collection: "选一款，马上玩",
    collectionText:
      "每款游戏都有操作、规则和技巧。双人游戏需要两人在同一设备上轮流或同时操作。",
    results: "符合条件的游戏",
    storageError: "浏览器未允许保存记录，本次仍可游玩。",
    score: "本次成绩",
    record: "本机上次成绩",
    noRecord: "完成一局后，这里会显示游戏返回的成绩。",
    exit: "返回游戏列表",
    faq: "开始前你可能想知道",
    faq1: "需要注册吗？",
    answer1:
      "不需要。打开游戏后点击开始即可。收藏和部分游戏成绩保存在当前浏览器，不会在不同设备间同步。",
    faq2: "手机上也能玩吗？",
    answer2:
      "大多数游戏支持点击、滑动或屏幕按钮。太空射击需要键盘；复杂棋盘可单独打开游戏或使用横屏。各游戏操作说明会注明区别。",
    faq3: "为什么没有全站排行榜？",
    answer3:
      "本站目前没有在线账号或联网排行榜。我们只展示本机记录，不把本地数据称为全站排名。",
    updated: "内容更新",
    allGuides: "所有练习",
    complete: "查看解答",
    answer: "解答",
    check: "检验我的判断",
    next: "换一道例题",
    playNow: "进入完整游戏",
    retry: "游戏未能显示？可以重新加载或单独打开。",
    jump: "跳到正文",
    clearLocal: "清除本站收藏和游玩记录",
    cleared: "已清除收藏和游玩记录。游戏内部存档可在浏览器网站数据设置中清除。",
    collectionNone: "还没有记录。开始一款游戏，或点卡片上的收藏按钮。",
  },
  en: {
    lang: "en",
    home: "Games",
    learn: "Practice room",
    about: "About",
    privacy: "Privacy",
    feedback: "Report a problem",
    all: "All games",
    search: "Search games or controls",
    filter: "Choose a category",
    favorite: "Save",
    saved: "Saved",
    favorites: "Saved games",
    recent: "Recently played",
    local: "Saved games and play history stay in this browser.",
    start: "Start playing",
    ready: "Ready for a round?",
    load: "The game loads when you press Start. Check the controls before you play.",
    fullscreen: "Fullscreen",
    standalone: "Open game separately",
    restart: "Reload game",
    intro: "About this game",
    gameplay: "How to play",
    controls: "Controls",
    scoring: "Scoring and ending",
    tips: "Practical tips",
    related: "What to play next",
    guide: "Understand the move",
    guideIntro:
      "Try a worked example, then take one clear strategy into your next game.",
    minutes: "Short session",
    ownPace: "At your own pace",
    solo: "One player",
    duo: "Two players, one device",
    keyboard: "Keyboard",
    touch: "Touch controls",
    searchEmpty:
      "No matching games. Try a different term or clear the filters.",
    reset: "Clear filters",
    total: "games",
    hero: "Take a break.\nMake your next move.",
    promise:
      "Browser games with useful, specific guides. Find a small challenge for the time you have.",
    featured: "A good place to start",
    featuredText:
      "Merge, reason, remember. Learn one small skill at your own pace.",
    browse: "Browse all games",
    tryLesson: "Try an interactive lesson",
    collection: "Pick your next game",
    collectionText:
      "Every game includes controls, rules and practical tips. Two-player games are local: share a device with another person.",
    results: "matching games",
    storageError: "Your browser cannot save records. You can still play.",
    score: "Latest result",
    record: "Last result on this device",
    noRecord: "When a game reports a completed round, its result appears here.",
    exit: "Back to games",
    faq: "Before you start",
    faq1: "Do I need an account?",
    answer1:
      "No. Open a game and press Start. Saved games and some scores stay in this browser; they do not sync across devices.",
    faq2: "Can I play on a phone?",
    answer2:
      "Most games support taps, swipes or on-screen controls. Space Shooter requires a keyboard. For larger boards, open the game separately or turn your device sideways. Check each control guide.",
    faq3: "Is there a global leaderboard?",
    answer3:
      "There are no online accounts or shared leaderboards here. Personal device records are clearly labeled and are never presented as global rankings.",
    updated: "Updated",
    allGuides: "All lessons",
    complete: "Show explanation",
    answer: "Explanation",
    check: "Check my answer",
    next: "Next example",
    playNow: "Play the full game",
    retry: "Game not visible? Reload it or open it separately.",
    jump: "Skip to content",
    clearLocal: "Clear saved games and play history",
    cleared:
      "Saved games and play history cleared. Clear site data in your browser to remove individual game saves.",
    collectionNone:
      "Nothing here yet. Start a game or save a card to build your collection.",
  },
  ja: {
    lang: "ja",
    home: "ゲーム一覧",
    learn: "練習室",
    about: "このサイトについて",
    privacy: "プライバシー",
    feedback: "問題を報告",
    all: "すべて",
    search: "ゲーム名や操作で検索",
    filter: "ジャンルを選択",
    favorite: "保存",
    saved: "保存済み",
    favorites: "お気に入り",
    recent: "最近遊んだゲーム",
    local: "お気に入りと履歴は、このブラウザだけに保存されます。",
    start: "ゲームを開始",
    ready: "一局、遊びませんか？",
    load: "開始ボタンを押すとゲームが読み込まれます。先に操作を確認しましょう。",
    fullscreen: "全画面",
    standalone: "ゲームを別画面で開く",
    restart: "再読み込み",
    intro: "ゲーム紹介",
    gameplay: "遊び方",
    controls: "操作",
    scoring: "得点と終了条件",
    tips: "上達のヒント",
    related: "次に遊ぶゲーム",
    guide: "考えてから、動かそう",
    guideIntro: "操作できる例題でルールを理解し、次の一局に生かしましょう。",
    minutes: "短時間",
    ownPace: "自分のペースで",
    solo: "1人",
    duo: "同じ端末で2人",
    keyboard: "キーボード",
    touch: "タッチ対応",
    searchEmpty:
      "該当するゲームがありません。検索語を変えるか条件を解除してください。",
    reset: "条件を解除",
    total: "ゲーム",
    hero: "ひと休み。\n次の一手を楽しもう。",
    promise:
      "ダウンロード不要のゲームと具体的な遊び方。今の気分に合う一局を選びましょう。",
    featured: "まずはこのゲームから",
    featuredText: "合体、推理、記憶。自分のペースで小さな目標に挑戦。",
    browse: "すべてのゲーム",
    tryLesson: "例題を試す",
    collection: "次のゲームを選ぼう",
    collectionText:
      "各ゲームに操作・ルール・ヒントがあります。2人用は、同じ端末を共有して遊びます。",
    results: "件のゲーム",
    storageError: "ブラウザに記録を保存できませんが、ゲームは遊べます。",
    score: "今回の記録",
    record: "この端末の前回記録",
    noRecord: "ゲームが終了結果を送信すると、ここに表示されます。",
    exit: "一覧へ戻る",
    faq: "始める前に",
    faq1: "登録は必要？",
    answer1:
      "不要です。ゲームを開いて開始してください。お気に入りと一部の得点はブラウザ内に保存され、端末間では同期しません。",
    faq2: "スマートフォンでも遊べる？",
    answer2:
      "多くのゲームはタップ・スワイプ・画面ボタンに対応しています。スペースシューターはキーボードが必要です。大きな盤面は別画面や横向きで遊んでください。",
    faq3: "世界ランキングはある？",
    answer3:
      "オンラインアカウントや共有ランキングはありません。この端末の記録だけを明記して表示します。",
    updated: "更新日",
    allGuides: "練習一覧",
    complete: "解説を見る",
    answer: "解説",
    check: "答えを確認",
    next: "次の例題",
    playNow: "ゲームで試す",
    retry: "表示されない場合は再読み込みするか別画面で開いてください。",
    jump: "本文へ",
    clearLocal: "お気に入りと履歴を消去",
    cleared:
      "お気に入りと履歴を消去しました。個別ゲームの保存内容はブラウザのサイトデータ設定から削除できます。",
    collectionNone:
      "まだ記録はありません。ゲームを開始するか、お気に入りに保存してください。",
  },
};
export const categories = {
  puzzle: ["益智", "Puzzles", "パズル"],
  arcade: ["街机", "Arcade", "アーケード"],
  racing: ["竞速", "Racing", "レース"],
  sports: ["体育", "Sports", "スポーツ"],
  board: ["棋盘", "Board games", "ボード"],
  casual: ["休闲", "Quick challenges", "ミニチャレンジ"],
};
